### ISSUE TITLE
BMR Shades

### ISSUE THREAD

**Issue by Juzas** [slesinger/HomeAssistant-BMR#5]
Hello,
I would like to ask about BMR component to HA.
Is it posible to implement BMR shades. I have excel sheet with modbus registres but i have problem with modbus TCP with HA and BMR.
Your integration works great with heating so I want to ask you about adding windows shade to integration.
Im from CR so we can conect in chzech.

Stepan Juza

**Comment by slesinger** [comment]
Hi Stepan, this integration does not use modbus but API calls. These are the same API calls that web UI is using. I do not have shades and cannot test it. I believe integration via API is possible. If you are interested, I can walk you through the code so that you can add your API calls and test it with your shades. I can share my contact.

**Comment by Juzas** [comment]
Hi
can you contact me by email to try implement BMR shades.
my email is juza.stepan@gmail.com

**Comment by slesinger** [comment]
I have sent you an email. Let's continue there.
