### ISSUE TITLE
Unable to install package pybmr>=0.7.1

### ISSUE THREAD

**Issue by jirrii** [slesinger/HomeAssistant-BMR#6]
Home Assistant BMR add-on stopped working after upgrading home assistant to version 2022.3.1

```
ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package pybmr>=0.7.1: ERROR: Cannot install pybmr==0.7.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by jirrii** [comment]
Your dependencies (and their version ranges) must be compatible with the dependencies Home Assistant has; otherwise, the installation of your custom integration will not succeed.
https://www.home-assistant.io/blog/2022/03/02/release-20223/

**Comment by jansemrad** [comment]
I experienced same problem, just to vorrect the version of core is 2022.3.1

**Comment by jirrii** [comment]
I have installed pybmr via SSH without depencies and it works.

**Comment by jansemrad** [comment]
How did you managed it, I am unable to run pip under SSH in HA Core?

**Comment by jirrii** [comment]
Do you have protection mode turned off in the SSH add-on settings?

**Comment by jirrii** [comment]
I run home assistant on my rapsberry pi (Home Assistant Operating System)
Try these commands in SSH terminal:
`docker exec -it homeassistant bash`
`pip install --no-deps pybmr`

**Comment by jansemrad** [comment]
Thank you this helped!!!

**Comment by maniac1234** [comment]
Hi,
I have the same problem with new 3.1 version HA. Addon BMR doesn´t work.
I found these errors in log.
Could you please send me short lama manual how to correct it?
Thank a lot

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 16:04:52 (5 occurrences)
Last logged: 16:16:56

Unable to install package pybmr>=0.7.1: ERROR: Cannot install pybmr==0.7.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

Logger: homeassistant.config
Source: config.py:873
First occurred: 16:05:50 (4 occurrences)
Last logged: 16:05:52

Platform error: binary_sensor - Requirements for bmr_hc64 not found: ['pybmr>=0.7.1'].
Platform error: sensor - Integration 'bmr_hc64' not found.
Platform error: climate - Integration 'bmr_hc64' not found.
Platform error: switch - Integration 'bmr_hc64' not found.

**Comment by jansemrad** [comment]
Go to Settings>AddOn, Install SSH & Web Terminal - configure it  (username and password) - described in Addon documantation.
Disable protection mode on Information tab of  the Addon and restart Addon. Then connect over SSH to your sever with SSH client e.g. Putty, login and enter:
`docker exec -it homeassistant bash`
and 
`pip install --no-deps pybmr`
Restart HA and BMR is working again. Until the pybmr will be updated you will need to enter those two lines over SSH every time you will update HA Core.

**Comment by maniac1234** [comment]
Trank you very much, It works! :)
Have a nice day

**Comment by zdeeenas** [comment]
Hi i have HA ver. 2022.10.5. I have problem wit instal BMR. Can you help me? Me email: zdeeenas@gmail.com [CZ]

**Comment by kyselyna** [comment]
hello I have a problem after installing the integration "local tuya" stopped working BMR inegration installation does not help even the above advice below I am sending a log extract

Logger: homeassistant.components.sensor
Source: custom_components/bmr_hc64/sensor.py:129
Integration: Senzor (documentation, issues)
First occurred: 00:38:11 (1 occurrences)
Last logged: 00:38:11

Error while setting up bmr_hc64 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmr_hc64/sensor.py", line 67, in setup_platform
    sensors.append(BmrCircuitTemperature(bmr, circuit_config))
  File "/config/custom_components/bmr_hc64/sensor.py", line 129, in __init__
    self._unique_id = f"{self._bmr.getUniqueId()}-sensor-{self._config.get(CONF_CIRCUIT_ID)}-temperature"
  File "/usr/local/lib/python3.10/site-packages/cachetools/__init__.py", line 702, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pybmr/__init__.py", line 46, in wrapped
    raise Exception("Authentication failed, check username/password")
Exception: Authentication failed, check username/password

**Comment by slesinger** [comment]
I have released 0.7.2 with bumbed version of certify. Can you tell if your issue is fixed?

**Comment by jansemrad** [comment]
Here are the logs:
`
Logger: homeassistant.config
Source: config.py:924
First occurred: 17:29:19 (4 occurrences)
Last logged: 17:32:37

Platform error: binary_sensor - Requirements for bmr_hc64 not found: ['pybmr>=0.7.1'].
Platform error: sensor - Integration 'bmr_hc64' not found.
Platform error: climate - Requirements for bmr_hc64 not found: ['pybmr>=0.7.1'].
Platform error: switch - Requirements for bmr_hc64 not found: ['pybmr>=0.7.1'].

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 17:28:35 (3 occurrences)
Last logged: 17:29:19

Unable to install package pybmr>=0.7.1: ERROR: Cannot install pybmr==0.7.1 and pybmr==0.7.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by slesinger** [comment]
I am not able to simulate it. Thanks for providing the workaround above. For me, I just installed pybmr==0.7.2 and that was it.

**Comment by Dehumanizer77** [comment]
I still have to install pybmr every time now after I upgrade HA. The error in logs is the same as was already pasted here, but when I enter the docker image, I am even able to install the pybmr without the --nodeps parameter...
It seems there are some conflicts with requests package, but still pybmr was installed just fine without --nodeps

``ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
zwave-me-ws 0.4.3 requires requests<3.0.0,>=2.28.1, but you have requests 2.28.0 which is incompatible.
nuheat 1.0.1 requires requests>=2.28.1, but you have requests 2.28.0 which is incompatible.
pyswitchbot 0.37.6 requires requests>=2.28.1, but you have requests 2.28.0 which is incompatible.
pyisy 3.1.14 requires requests>=2.28.1, but you have requests 2.28.0 which is incompatible.
locationsharinglib 5.0.1 requires cachetools>=5.3.0, but you have cachetools 4.2.4 which is incompatible.
locationsharinglib 5.0.1 requires requests>=2.28.2, but you have requests 2.28.0 which is incompatible.
homeassistant 2023.6.1 requires requests==2.31.0, but you have requests 2.28.0 which is incompatible.
Successfully installed cachetools-4.2.4 certifi-2021.10.8 charset-normalizer-2.0.9 idna-3.3 pybmr-0.7.2 requests-2.28.0 requests-toolbelt-0.9.1 urllib3-1.26.14``

when I then upgrade requests to 2.31.0, it says ``pybmr 0.7.2 requires requests==2.28.0, but you have requests 2.31.0 which is incompatible.`` 
So I feel the problem is with pybmr requiring requests exactly 2.28.0

Either way, HA and bmr works fine with both requests 2.28.0 and 2.31.0, despite the conflict errors. But it would be nice to fix it so that one wouldn't need to reinstall pybmr after every upgrade.
